"""add gas network tariffs

Revision ID: 1945a9d6a655
Revises: 7fcf48a92e13
Create Date: 2026-09-28 22:47:26.096775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1945a9d6a655'
down_revision: Union[str, Sequence[str], None] = '7fcf48a92e13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gas_network_tariffs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('network_area', sa.String(length=255), nullable=False),
    sa.Column('network_level', sa.Integer(), nullable=False),
    sa.Column('tariff_variant', sa.String(length=50), nullable=False),
    sa.Column('consumption_from_kwh', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('consumption_to_kwh', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('arbeitspreis_cent_kwh', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('leistungspreis_cent_kwh_h', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('pauschale_cent_year', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year', 'network_area', 'network_level', 'tariff_variant', 'consumption_from_kwh', name='uq_gas_network_tariff')
    )
    op.create_index(op.f('ix_gas_network_tariffs_id'), 'gas_network_tariffs', ['id'], unique=False)
    op.create_index(op.f('ix_gas_network_tariffs_network_area'), 'gas_network_tariffs', ['network_area'], unique=False)
    op.create_index(op.f('ix_gas_network_tariffs_year'), 'gas_network_tariffs', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gas_network_tariffs_year'), table_name='gas_network_tariffs')
    op.drop_index(op.f('ix_gas_network_tariffs_network_area'), table_name='gas_network_tariffs')
    op.drop_index(op.f('ix_gas_network_tariffs_id'), table_name='gas_network_tariffs')
    op.drop_table('gas_network_tariffs')
    # ### end Alembic commands ###
