"""add contract status history

Revision ID: 38517c97db42
Revises: 10f436647da1
Create Date: 2026-09-04 22:51:28.861541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38517c97db42'
down_revision: Union[str, Sequence[str], None] = '10f436647da1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contract_status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('changed_by_user_id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contract_status_history_changed_by_user_id'), 'contract_status_history', ['changed_by_user_id'], unique=False)
    op.create_index(op.f('ix_contract_status_history_contract_id'), 'contract_status_history', ['contract_id'], unique=False)
    op.create_index(op.f('ix_contract_status_history_id'), 'contract_status_history', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contract_status_history_id'), table_name='contract_status_history')
    op.drop_index(op.f('ix_contract_status_history_contract_id'), table_name='contract_status_history')
    op.drop_index(op.f('ix_contract_status_history_changed_by_user_id'), table_name='contract_status_history')
    op.drop_table('contract_status_history')
    # ### end Alembic commands ###
