"""add provider logo

Revision ID: 3e6a9d9418b2
Revises: f223a86743c1
Create Date: 2026-10-05 17:58:10.619289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e6a9d9418b2'
down_revision: Union[str, Sequence[str], None] = 'f223a86743c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('providers', sa.Column('logo_url', sa.String(length=500), nullable=True))
    op.drop_index(op.f('ix_usage_fee_rules_lookup'), table_name='usage_fee_rules')
    op.create_index(op.f('ix_usage_fee_rules_id'), 'usage_fee_rules', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usage_fee_rules_id'), table_name='usage_fee_rules')
    op.create_index(op.f('ix_usage_fee_rules_lookup'), 'usage_fee_rules', ['gkz', 'network_operator_id', 'energy_type'], unique=False)
    op.drop_column('providers', 'logo_url')
    # ### end Alembic commands ###
