"""add gkz and municipality to postal codes

Revision ID: 406f981fb72b
Revises: 602a6df0152e
Create Date: 2026-09-21 19:08:11.818776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '406f981fb72b'
down_revision: Union[str, Sequence[str], None] = '602a6df0152e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('postal_codes', sa.Column('gkz', sa.String(length=10), nullable=True))
    op.add_column('postal_codes', sa.Column('municipality', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_postal_codes_gkz'), 'postal_codes', ['gkz'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_postal_codes_gkz'), table_name='postal_codes')
    op.drop_column('postal_codes', 'municipality')
    op.drop_column('postal_codes', 'gkz')
    # ### end Alembic commands ###
