"""add sne network area to network operators

Revision ID: 602a6df0152e
Revises: f3d7e591f7fc
Create Date: 2026-09-21 00:42:16.820145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '602a6df0152e'
down_revision: Union[str, Sequence[str], None] = 'f3d7e591f7fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('network_operators', sa.Column('sne_network_area', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('network_operators', 'sne_network_area')
    # ### end Alembic commands ###
