"""add network operator dropdown mappings

Revision ID: 8030d6058006
Revises: ab1c65909a5e
Create Date: 2026-09-25 01:10:27.205143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8030d6058006'
down_revision: Union[str, Sequence[str], None] = 'ab1c65909a5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('network_operator_dropdown_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('network_operator_identifier_id', sa.Integer(), nullable=False),
    sa.Column('bundesland', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('standard_visible', sa.Boolean(), nullable=False),
    sa.Column('source_status', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['network_operator_identifier_id'], ['network_operator_identifiers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('network_operator_identifier_id', 'bundesland', name='uq_network_operator_dropdown_identifier_bundesland')
    )
    op.create_index(op.f('ix_network_operator_dropdown_mappings_bundesland'), 'network_operator_dropdown_mappings', ['bundesland'], unique=False)
    op.create_index(op.f('ix_network_operator_dropdown_mappings_id'), 'network_operator_dropdown_mappings', ['id'], unique=False)
    op.create_index(op.f('ix_network_operator_dropdown_mappings_network_operator_identifier_id'), 'network_operator_dropdown_mappings', ['network_operator_identifier_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_network_operator_dropdown_mappings_network_operator_identifier_id'), table_name='network_operator_dropdown_mappings')
    op.drop_index(op.f('ix_network_operator_dropdown_mappings_id'), table_name='network_operator_dropdown_mappings')
    op.drop_index(op.f('ix_network_operator_dropdown_mappings_bundesland'), table_name='network_operator_dropdown_mappings')
    op.drop_table('network_operator_dropdown_mappings')
    # ### end Alembic commands ###
