"""add commission entries and monthly settlements

Revision ID: 83ddf6b0dd66
Revises: 69c1006ab9dd
Create Date: 2026-09-05 20:36:53.111119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83ddf6b0dd66'
down_revision: Union[str, Sequence[str], None] = '69c1006ab9dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monthly_settlements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id', 'year', 'month', name='uq_monthly_settlement_agent_period')
    )
    op.create_index(op.f('ix_monthly_settlements_agent_id'), 'monthly_settlements', ['agent_id'], unique=False)
    op.create_index(op.f('ix_monthly_settlements_id'), 'monthly_settlements', ['id'], unique=False)
    op.create_table('commission_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('source_document_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.ForeignKeyConstraint(['source_document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commission_entries_agent_id'), 'commission_entries', ['agent_id'], unique=False)
    op.create_index(op.f('ix_commission_entries_contract_id'), 'commission_entries', ['contract_id'], unique=False)
    op.create_index(op.f('ix_commission_entries_id'), 'commission_entries', ['id'], unique=False)
    op.create_index(op.f('ix_commission_entries_provider_id'), 'commission_entries', ['provider_id'], unique=False)
    op.create_table('monthly_settlement_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('settlement_id', sa.Integer(), nullable=False),
    sa.Column('commission_entry_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['commission_entry_id'], ['commission_entries.id'], ),
    sa.ForeignKeyConstraint(['settlement_id'], ['monthly_settlements.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('commission_entry_id', name='uq_monthly_settlement_item_commission')
    )
    op.create_index(op.f('ix_monthly_settlement_items_commission_entry_id'), 'monthly_settlement_items', ['commission_entry_id'], unique=False)
    op.create_index(op.f('ix_monthly_settlement_items_id'), 'monthly_settlement_items', ['id'], unique=False)
    op.create_index(op.f('ix_monthly_settlement_items_settlement_id'), 'monthly_settlement_items', ['settlement_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_monthly_settlement_items_settlement_id'), table_name='monthly_settlement_items')
    op.drop_index(op.f('ix_monthly_settlement_items_id'), table_name='monthly_settlement_items')
    op.drop_index(op.f('ix_monthly_settlement_items_commission_entry_id'), table_name='monthly_settlement_items')
    op.drop_table('monthly_settlement_items')
    op.drop_index(op.f('ix_commission_entries_provider_id'), table_name='commission_entries')
    op.drop_index(op.f('ix_commission_entries_id'), table_name='commission_entries')
    op.drop_index(op.f('ix_commission_entries_contract_id'), table_name='commission_entries')
    op.drop_index(op.f('ix_commission_entries_agent_id'), table_name='commission_entries')
    op.drop_table('commission_entries')
    op.drop_index(op.f('ix_monthly_settlements_id'), table_name='monthly_settlements')
    op.drop_index(op.f('ix_monthly_settlements_agent_id'), table_name='monthly_settlements')
    op.drop_table('monthly_settlements')
    # ### end Alembic commands ###
