"""add network metering fees

Revision ID: 98cbdad66faf
Revises: f5f7fb6eb242
Create Date: 2026-09-21 00:25:00.238271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98cbdad66faf'
down_revision: Union[str, Sequence[str], None] = 'f5f7fb6eb242'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('network_metering_fees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('network_operator_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('meter_type', sa.String(length=50), nullable=False),
    sa.Column('annual_fee', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['network_operator_id'], ['network_operators.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('network_operator_id', 'year', 'meter_type', name='uq_network_metering_fee')
    )
    op.create_index(op.f('ix_network_metering_fees_id'), 'network_metering_fees', ['id'], unique=False)
    op.create_index(op.f('ix_network_metering_fees_network_operator_id'), 'network_metering_fees', ['network_operator_id'], unique=False)
    op.create_index(op.f('ix_network_metering_fees_year'), 'network_metering_fees', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_network_metering_fees_year'), table_name='network_metering_fees')
    op.drop_index(op.f('ix_network_metering_fees_network_operator_id'), table_name='network_metering_fees')
    op.drop_index(op.f('ix_network_metering_fees_id'), table_name='network_metering_fees')
    op.drop_table('network_metering_fees')
    # ### end Alembic commands ###
