"""add network operator identifiers

Revision ID: ab1c65909a5e
Revises: 5e5d6e38ec53
Create Date: 2026-09-24 21:11:30.591787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab1c65909a5e'
down_revision: Union[str, Sequence[str], None] = '5e5d6e38ec53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('network_operator_identifiers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('network_operator_id', sa.Integer(), nullable=False),
    sa.Column('energy_type', sa.String(length=20), nullable=False),
    sa.Column('zpn_prefix', sa.String(length=8), nullable=False),
    sa.Column('bundesland', sa.String(length=50), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['network_operator_id'], ['network_operators.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('energy_type', 'zpn_prefix', name='uq_network_operator_identifier_energy_prefix')
    )
    op.create_index(op.f('ix_network_operator_identifiers_bundesland'), 'network_operator_identifiers', ['bundesland'], unique=False)
    op.create_index(op.f('ix_network_operator_identifiers_energy_type'), 'network_operator_identifiers', ['energy_type'], unique=False)
    op.create_index(op.f('ix_network_operator_identifiers_id'), 'network_operator_identifiers', ['id'], unique=False)
    op.create_index(op.f('ix_network_operator_identifiers_network_operator_id'), 'network_operator_identifiers', ['network_operator_id'], unique=False)
    op.create_index(op.f('ix_network_operator_identifiers_zpn_prefix'), 'network_operator_identifiers', ['zpn_prefix'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_network_operator_identifiers_zpn_prefix'), table_name='network_operator_identifiers')
    op.drop_index(op.f('ix_network_operator_identifiers_network_operator_id'), table_name='network_operator_identifiers')
    op.drop_index(op.f('ix_network_operator_identifiers_id'), table_name='network_operator_identifiers')
    op.drop_index(op.f('ix_network_operator_identifiers_energy_type'), table_name='network_operator_identifiers')
    op.drop_index(op.f('ix_network_operator_identifiers_bundesland'), table_name='network_operator_identifiers')
    op.drop_table('network_operator_identifiers')
    # ### end Alembic commands ###
