"""add network operator coverage

Revision ID: bc5577f9bbc1
Revises: 406f981fb72b
Create Date: 2026-09-21 20:31:29.647629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc5577f9bbc1'
down_revision: Union[str, Sequence[str], None] = '406f981fb72b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('network_operator_coverage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('network_operator_id', sa.Integer(), nullable=False),
    sa.Column('gkz', sa.String(length=10), nullable=False),
    sa.Column('postal_code', sa.String(length=10), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('street_code', sa.String(length=20), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['network_operator_id'], ['network_operators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_network_operator_coverage_gkz'), 'network_operator_coverage', ['gkz'], unique=False)
    op.create_index(op.f('ix_network_operator_coverage_id'), 'network_operator_coverage', ['id'], unique=False)
    op.create_index('ix_network_operator_coverage_lookup', 'network_operator_coverage', ['gkz', 'postal_code', 'city', 'street_code'], unique=False)
    op.create_index(op.f('ix_network_operator_coverage_network_operator_id'), 'network_operator_coverage', ['network_operator_id'], unique=False)
    op.create_index(op.f('ix_network_operator_coverage_postal_code'), 'network_operator_coverage', ['postal_code'], unique=False)
    op.create_index(op.f('ix_network_operator_coverage_street_code'), 'network_operator_coverage', ['street_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_network_operator_coverage_street_code'), table_name='network_operator_coverage')
    op.drop_index(op.f('ix_network_operator_coverage_postal_code'), table_name='network_operator_coverage')
    op.drop_index(op.f('ix_network_operator_coverage_network_operator_id'), table_name='network_operator_coverage')
    op.drop_index('ix_network_operator_coverage_lookup', table_name='network_operator_coverage')
    op.drop_index(op.f('ix_network_operator_coverage_id'), table_name='network_operator_coverage')
    op.drop_index(op.f('ix_network_operator_coverage_gkz'), table_name='network_operator_coverage')
    op.drop_table('network_operator_coverage')
    # ### end Alembic commands ###
