"""add tariff network operators

Revision ID: cb4e5d178a24
Revises: d0df5bcff436
Create Date: 2026-09-07 23:40:29.589544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb4e5d178a24'
down_revision: Union[str, Sequence[str], None] = 'd0df5bcff436'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tariff_network_operators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tariff_id', sa.Integer(), nullable=False),
    sa.Column('network_operator_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['network_operator_id'], ['network_operators.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tariff_id'], ['tariffs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tariff_id', 'network_operator_id', name='uq_tariff_network_operator')
    )
    op.create_index(op.f('ix_tariff_network_operators_id'), 'tariff_network_operators', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tariff_network_operators_id'), table_name='tariff_network_operators')
    op.drop_table('tariff_network_operators')
    # ### end Alembic commands ###
