"""add SNE tariffs

Revision ID: cd088bfe6335
Revises: caf044d15d5f
Create Date: 2026-09-21 00:01:31.763107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd088bfe6335'
down_revision: Union[str, Sequence[str], None] = 'caf044d15d5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sne_tariffs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('network_level', sa.Integer(), nullable=False),
    sa.Column('tariff_type', sa.String(length=50), nullable=False),
    sa.Column('network_area', sa.String(length=255), nullable=False),
    sa.Column('lp_cent', sa.Float(), nullable=True),
    sa.Column('ap_cent_kwh', sa.Float(), nullable=True),
    sa.Column('snap_cent_kwh', sa.Float(), nullable=True),
    sa.Column('dtap_cent_kwh', sa.Float(), nullable=True),
    sa.Column('dnap_cent_kwh', sa.Float(), nullable=True),
    sa.Column('network_loss_cent_kwh', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year', 'network_level', 'tariff_type', 'network_area', name='uq_sne_tariff')
    )
    op.create_index(op.f('ix_sne_tariffs_id'), 'sne_tariffs', ['id'], unique=False)
    op.create_index(op.f('ix_sne_tariffs_year'), 'sne_tariffs', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sne_tariffs_year'), table_name='sne_tariffs')
    op.drop_index(op.f('ix_sne_tariffs_id'), table_name='sne_tariffs')
    op.drop_table('sne_tariffs')
    # ### end Alembic commands ###
