"""add network operators and postal codes

Revision ID: d0df5bcff436
Revises: 83ddf6b0dd66
Create Date: 2026-09-06 19:24:45.395462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0df5bcff436'
down_revision: Union[str, Sequence[str], None] = '83ddf6b0dd66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('network_operators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_network_operators_id'), 'network_operators', ['id'], unique=False)
    op.create_table('postal_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('postal_code', sa.String(length=10), nullable=False),
    sa.Column('city', sa.String(length=255), nullable=False),
    sa.Column('network_operator_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['network_operator_id'], ['network_operators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_postal_codes_id'), 'postal_codes', ['id'], unique=False)
    op.create_index(op.f('ix_postal_codes_postal_code'), 'postal_codes', ['postal_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_postal_codes_postal_code'), table_name='postal_codes')
    op.drop_index(op.f('ix_postal_codes_id'), table_name='postal_codes')
    op.drop_table('postal_codes')
    op.drop_index(op.f('ix_network_operators_id'), table_name='network_operators')
    op.drop_table('network_operators')
    # ### end Alembic commands ###
