"""add tariff documents

Revision ID: f223a86743c1
Revises: 512ec93bbba6
Create Date: 2026-10-03 23:12:28.463294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f223a86743c1'
down_revision: Union[str, Sequence[str], None] = '512ec93bbba6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tariff_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tariff_id', sa.Integer(), nullable=False),
    sa.Column('uploaded_by_user_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.Enum('PRICE_SHEET', 'AGB', 'POWER_OF_ATTORNEY', 'FORM', 'OTHER', name='tariffdocumenttype'), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tariff_id'], ['tariffs.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tariff_documents_id'), 'tariff_documents', ['id'], unique=False)
    op.create_index(op.f('ix_tariff_documents_tariff_id'), 'tariff_documents', ['tariff_id'], unique=False)
    op.create_index(op.f('ix_tariff_documents_uploaded_by_user_id'), 'tariff_documents', ['uploaded_by_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tariff_documents_uploaded_by_user_id'), table_name='tariff_documents')
    op.drop_index(op.f('ix_tariff_documents_tariff_id'), table_name='tariff_documents')
    op.drop_index(op.f('ix_tariff_documents_id'), table_name='tariff_documents')
    op.drop_table('tariff_documents')
    # ### end Alembic commands ###
