"""add regulatory charges

Revision ID: f3d7e591f7fc
Revises: 98cbdad66faf
Create Date: 2026-09-21 00:32:11.149536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3d7e591f7fc'
down_revision: Union[str, Sequence[str], None] = '98cbdad66faf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regulatory_charges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('calculation_type', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('network_level', sa.Integer(), nullable=True),
    sa.Column('tariff_type', sa.String(length=50), nullable=True),
    sa.Column('network_area', sa.String(length=255), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'calculation_type', 'network_level', 'tariff_type', 'network_area', 'valid_from', name='uq_regulatory_charge')
    )
    op.create_index(op.f('ix_regulatory_charges_id'), 'regulatory_charges', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_regulatory_charges_id'), table_name='regulatory_charges')
    op.drop_table('regulatory_charges')
    # ### end Alembic commands ###
