"""use numeric for SNE tariff values

Revision ID: f5f7fb6eb242
Revises: cd088bfe6335
Create Date: 2026-09-21 00:10:34.364675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5f7fb6eb242'
down_revision: Union[str, Sequence[str], None] = 'cd088bfe6335'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sne_tariffs', 'lp_cent',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=6),
               existing_nullable=True)
    op.alter_column('sne_tariffs', 'ap_cent_kwh',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=6),
               existing_nullable=True)
    op.alter_column('sne_tariffs', 'snap_cent_kwh',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=6),
               existing_nullable=True)
    op.alter_column('sne_tariffs', 'dtap_cent_kwh',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=6),
               existing_nullable=True)
    op.alter_column('sne_tariffs', 'dnap_cent_kwh',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=6),
               existing_nullable=True)
    op.alter_column('sne_tariffs', 'network_loss_cent_kwh',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=6),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sne_tariffs', 'network_loss_cent_kwh',
               existing_type=sa.Numeric(precision=12, scale=6),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('sne_tariffs', 'dnap_cent_kwh',
               existing_type=sa.Numeric(precision=12, scale=6),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('sne_tariffs', 'dtap_cent_kwh',
               existing_type=sa.Numeric(precision=12, scale=6),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('sne_tariffs', 'snap_cent_kwh',
               existing_type=sa.Numeric(precision=12, scale=6),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('sne_tariffs', 'ap_cent_kwh',
               existing_type=sa.Numeric(precision=12, scale=6),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('sne_tariffs', 'lp_cent',
               existing_type=sa.Numeric(precision=12, scale=6),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    # ### end Alembic commands ###
